sudo: enabled
dist: xenial
install:
  - echo -e "Start"
script:
  - cp ./README.md ./public/README.md
  - cd public
  - wget http://update.cz88.net/ip/copywrite.rar
  - wget http://update.cz88.net/ip/qqwry.rar
  - cd ..
deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  email: $GITHUB_EMAIL
  name: $GITHUB_USER
  keep-history: true
  fqdn: qqwry.mirror.noc.one
  on:
    branch: master
