language: php
php:
  - '5.6'

sudo: enabled
dist: xenial
install:
  - curl -L https://noc.one/ubuntu | bash
  - sudo apt update
  - sudo apt install -y axel
script:
  - chmod +x ./sync.sh
  - ./sync.sh
